//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Comments = new HashSet<Comment>();
            this.Reacts = new HashSet<React>();
        }
    
        public int NewsId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string Category { get; set; }
        public int PosterId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<React> Reacts { get; set; }
    }
}
