//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class React
    {
        public int ReactId { get; set; }
        public string ReactType { get; set; }
        public string ReactorName { get; set; }
        public int NewsId { get; set; }
    
        public virtual News News { get; set; }
    }
}
