//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dob { get; set; }
        public string Gender { get; set; }
        public double Cgpa { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual department department { get; set; }
    }
}
